### PR TITLE
fix: Image copy option selection bug resolution

### PR DESCRIPTION
**Pull request by userJu**
### ⛱️ Major Changes
- inject index value if clickCopyUrl changes before state change
- Change Spring REST icon slug accordingly to the test

before
ezgif com-video-to-gif (7)

after
ezgif com-video-to-gif (6)

### CODE REVIEW

**Comment by msdio** [comment]
Can you give more information about problem and how you solved it? I can't get what the problem is.

**Review by msdio — CHANGES_REQUESTED** [review]
Can you give more information about problem and how you solved it? I can't get what the problem is.

**Comment by userJu** [comment]
> Can you give more information about problem and how you solved it? I can't get what the problem is.

If you select the button sub-list for both the before and after screens, the url is copied.
However, when selecting the button sub-list, the previously selected button ex) copy image tag is copied in the previously selected copy link-only manner.

I defined this problem as being caused by copying url through a function that uses state before state is updated.
therefore
- By optionally putting index elements in clickCopyUrl that copies url,
- When the button sublist was selected, the index value determined the copy condition.😁✨

**Review by msdio — COMMENTED** [review]
Thank you for detecting critical issue!

You used index and check whether it is undefined, but I think you can resolve this issue in some different way.

I'm not saying that your code is bad, but I think keep attaching small codes for solving bugs will slowly make code unreadable.

How about re-constructure code for fix issue and also make code look keep neat?
I'm suggesting some ways you can fix this issue.

## Understand why it is happening
This is occuring because `state`(in this code, selectedOption) is not changed before clipboard action. So we need to do clipboard things **after state is changed**.

These are some possible ways that comes immediately in my mind.
### 1. useEffect
```tsx
useEffect(() => {
  clickCopyUrl();
}, [selectedOption]);
```
it will ensure that we can get fresh option that user selected. but it will copy two times(render -> change state -> re-render). But it is the easiest way and also intuitive.

### 2. useRef
store selected option in useRef variable and use it as `refVariable.current` will ensure that we get updated value.

### 3. functional update
one way to change state immediately is using `functional update`.

I believe that you will find way better solution than current one!

**Comment by userJu** [comment]
> I'm not saying that your code is bad, but I think **keep attaching small codes for solving bugs will slowly make code unreadable.**
> 


Thank you for reviewing what I didn't consider!

I refactored with code that changes the current value of the selected option using useRef!

Surely it seems better for code understanding and neat code to update the required value with or without rendering using useRef than to divide the function into two (with or without index)!
Thank you 😊🍄

**Review by msdio — APPROVED** [review]
This is exactly what I meant!

Thank you for reporting issue :)

**Pull request merged**
